import { openai } from "@workspace/integrations-openai-ai-server";
import { logger } from "./logger";

const THREAT_THEMES = [
  "фишинговые письма и SMS-рассылки",
  "поддельные сайты банков и госуслуг",
  "мошенничество в мессенджерах (Telegram, WhatsApp)",
  "кражи аккаунтов через поддельные формы входа",
  "вредоносные приложения в Google Play и App Store",
  "схемы «ваш родственник попал в беду»",
  "фейковые розыгрыши и лотереи в соцсетях",
  "утечки паролей и продажа данных в даркнете",
  "поддельные QR-коды в общественных местах",
  "вишинг — мошенничество по телефону от «банков»",
  "шантаж через взломанные веб-камеры",
  "мошенничество с криптовалютами и NFT",
  "поддельные сайты авиабилетов и отелей",
  "кража данных карт через заражённые терминалы",
];

function getTodayTheme(): string {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) /
      (1000 * 60 * 60 * 24)
  );
  return THREAT_THEMES[dayOfYear % THREAT_THEMES.length]!;
}

export async function generateDailyNews(): Promise<string | null> {
  const theme = getTodayTheme();

  const systemPrompt = `Ты — редактор канала OpenClaw о цифровой безопасности в Telegram.
Пишешь на русском языке. Аудитория — подростки и взрослые без технических знаний.
Стиль: живой, конкретный, чуть тревожный, но без паники.
Никакого Markdown, никаких звёздочек (**). Только чистый текст.`;

  const userPrompt = `Напиши короткую рубрику "🔥 Угроза дня" по теме: ${theme}.

Структура (строго без заголовков и нумерации, просто абзацы):
1. Одно предложение — суть угрозы (что происходит прямо сейчас).
2. Конкретный пример — как именно атакуют жертву (1-2 предложения).
3. Один простой совет — как защититься (1 предложение).

Максимум 5 предложений всего. Без вводных слов типа «Итак» или «Сегодня поговорим».`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-5-mini",
      max_completion_tokens: 256,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
    });

    const text = response.choices[0]?.message?.content?.trim();
    if (!text) throw new Error("Empty AI response");

    logger.info({ theme }, "Daily news generated by AI");
    return `🔥 <b>Угроза дня</b>\n\n${text}`;
  } catch (err) {
    logger.warn({ err, theme }, "AI daily news failed — skipping");
    return null;
  }
}
